AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  color-extractor

  Sample SAM Template for color-extractor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
    MemorySize: 2048

Resources:
  SrcBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: color-quantization-input
  OutBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: color-quantization-output

  QuantizedImageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["app.lambda_handler"]
      Environment:
        Variables:
          TARGET_BUCKET: !Ref OutBucket
          MAX_CLUSTERS: 32
      Policies:
      - S3WritePolicy:
          BucketName: color-quantization-output
      - S3ReadPolicy: 
          BucketName: color-quantization-input

      Events:
        QuantizedImageEvent:
          Type: S3 
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*
    Metadata:
      DockerTag: v1
      DockerContext: .
      Dockerfile : Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  QuantizedImageFunction:
    Description: "QuantizedImage Lambda Function ARN"
    Value: !GetAtt QuantizedImageFunction.Arn
  QuantizedImageFunctionIamRole:
    Description: "Implicit IAM Role created for QuantizedImage function"
    Value: !GetAtt QuantizedImageFunctionRole.Arn
